import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../..');
const run = JSON.parse(readFileSync(join(here, 'run.json'), 'utf8'));
const inputs = JSON.parse(readFileSync(join(here, 'inputs.json'), 'utf8'));
const sha256 = path => createHash('sha256').update(readFileSync(path)).digest('hex');
if (sha256(join(here, 'BRIEF.md')) !== inputs.briefSha256) throw new Error('The common brief changed during the run.');
for (const input of inputs.references) {
  if (sha256(join(root, input.path)) !== input.sha256) throw new Error(`Common input changed: ${input.path}`);
}
for (const participant of run.participants) {
  const manifest = JSON.parse(readFileSync(join(here, participant.folder, 'manifest.json'), 'utf8'));
  const validation = JSON.parse(readFileSync(join(here, participant.folder, 'validation.json'), 'utf8'));
  if (validation.length !== 3 || validation.some(result => result.issues.length)) throw new Error(`${participant.folder}: rendering validation is incomplete`);
  for (const concept of manifest.concepts) {
    if (!existsSync(join(here, participant.folder, `${concept.id}.png`))) throw new Error(`Missing ${participant.folder}/${concept.id}.png`);
  }
  participant.concepts = manifest.concepts;
  participant.notes = manifest.notes || '';
  participant.validation = validation;
}
run.inputs = inputs;
writeFileSync(join(here, 'data.js'), `/* Generated by build-gallery.mjs from run.json and participant manifests. */\nwindow.PLAYBOOK_COMPARISON = ${JSON.stringify(run, null, 2)};\n`);
const escape = text => String(text).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const rows = run.categories.map(category => `<section class="sheet-row"><h2>${escape(category.label)}</h2><div class="sheet-cards">${run.participants.map(participant => {
  const concept = participant.concepts.find(item => item.id === category.id);
  return `<img src="${participant.folder}/${concept.id}.png" width="1080" height="1350" alt="${escape(`${participant.label}: ${concept.alt}`)}">`;
}).join('')}</div></section>`).join('\n');
writeFileSync(join(here, 'contact-sheet.html'), `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>Playbook — Nine model concepts</title>
<link rel="stylesheet" href="../brand-inject.css"><link rel="stylesheet" href="fonts.css">
<style>
*{box-sizing:border-box}body{margin:0;background:var(--pb-color-neutral-50);color:var(--pb-color-primary);font-family:var(--pb-font-body)}
.sheet{width:1600px;padding:44px 48px 30px}.sheet-header{display:flex;justify-content:space-between;align-items:baseline;border-bottom:2px solid var(--pb-color-primary);padding-bottom:24px;margin-bottom:24px;gap:40px}
h1{font:700 36px/1.1 var(--pb-font-heading);letter-spacing:-.035em;margin:0}.sheet-header p{font-size:22px;margin:0}
.sheet-models,.sheet-cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}.sheet-models strong{font:700 27px/1.2 var(--pb-font-heading);letter-spacing:-.025em}
.sheet-row{margin-top:24px}.sheet-row h2{font:600 22px/1.2 var(--pb-font-heading);margin:0 0 12px}.sheet-cards img{width:100%;height:auto;display:block}
.sheet-footer{display:flex;justify-content:space-between;gap:24px;border-top:1px solid var(--pb-color-neutral-300);padding-top:20px;margin-top:28px;font-size:21px}
</style></head><body><main class="sheet"><header class="sheet-header"><h1>Playbook / One brief. Three models.</h1><p>Same brand content &amp; templates · High reasoning</p></header>
<div class="sheet-models">${run.participants.map(p => `<strong>${escape(p.label)}</strong>`).join('')}</div>
${rows}
<footer class="sheet-footer"><span>Nine independent concepts · 1080 × 1350 originals</span><span>Model-authored outputs after factual and visual QA</span></footer></main></body></html>\n`);
console.log(`Gallery data built: ${run.participants.length} models, ${run.participants.reduce((sum, p) => sum + p.concepts.length, 0)} concepts. All common input hashes match.`);
