/* Generated by build-gallery.mjs from run.json and participant manifests. */
window.PLAYBOOK_COMPARISON = {
  "title": "Playbook exploratory model concept showcase",
  "date": "2026-09-04",
  "format": {
    "width": 1080,
    "height": 1350,
    "language": "en",
    "tier": 1
  },
  "participants": [
    {
      "folder": "astra",
      "label": "GPT-6 Astra",
      "model": "gpt-6-astra",
      "reasoning": "high",
      "blindLabel": "Studio A",
      "concepts": [
        {
          "id": "sports",
          "category": "sports",
          "title": "A payout isn’t all profit.",
          "rationale": "A branching money diagram separates the headline payout into the original stake and actual profit. The two pockets make a common odds-reading distinction visible at a glance.",
          "caption": "That payout includes some money you already put in. Example: a $10 bet at +150 returns $25 if it wins — $10 stake back, plus $15 profit. If it loses, the $10 stake is lost. Separate the stake from the profit when you read the numbers.",
          "alt": "Playbook sports math card on navy. Headline: A payout isn’t all profit. Example: a $10 bet at +150 odds. A diagram branches from $25, total back if your bet wins, into $10, your stake back, and +$15, your profit. Text: The payout includes the money you put in. If the bet loses, it’s gone. Action: Separate the stake from the profit. A protected footer displays free support and age information from the brand configuration.",
          "sources": [
            {
              "path": "how-to-play/sports-betting.md",
              "section": "American odds (moneyline)",
              "note": "The +150 definition gives $150 profit per $100 stake. Scaling by one tenth gives $15 profit on $10. Adding the returned $10 stake gives $25 total return; both the stake and odds are visible on the card."
            },
            {
              "path": "how-to-play/sports-betting.md",
              "section": "The basics",
              "note": "Under How it works, an incorrect bet loses the stake. The card states this alongside the winning-return example."
            }
          ],
          "tags": {
            "content_type": "quick-reference",
            "pillar": [
              "open"
            ],
            "tier": 1,
            "tone": "confident-informative",
            "audience": [
              "general",
              "sports-bettors"
            ],
            "channel": [
              "social-media"
            ],
            "reading_level": "grade-6-8"
          }
        },
        {
          "id": "myth",
          "category": "myth",
          "title": "“Almost” isn’t a forecast.",
          "rationale": "A near-miss display becomes an interrupted prediction arrow. The weather-forecast hook gives the myth a memorable label without mocking the player or suggesting a technique for winning.",
          "caption": "Two matching symbols can feel like a hint. They aren’t a forecast. A near miss doesn’t make the next slot spin more likely to win: each spin is independent. Share the fact next time “almost” lands.",
          "alt": "Playbook myth/fact card on a pale background. Headline: “Almost” isn’t a forecast. A navy panel labeled Illustration: a non-winning spin shows two matching seven symbols and a diamond. A crossed arrow accompanies No preview of the next spin. Text: A near miss doesn’t make the next spin more likely to win. Each spin is independent. Action: Share this next time “almost” lands. A protected navy footer displays free support and age information from the brand configuration.",
          "sources": [
            {
              "path": "messaging/myth-busting.md",
              "section": "Myth 4: Near Misses Mean You're Close",
              "note": "The article and quiz explain that near misses carry no predictive information and that the next spin is independent. The artwork explicitly labels its invented reel combination a non-winning illustration rather than claiming a universal paytable rule."
            },
            {
              "path": "how-to-play/slots.md",
              "section": "Tips for informed play",
              "note": "Tip 5 states that previous spin results do not affect the next spin. No numerical probability is inferred from the pictured symbols."
            }
          ],
          "tags": {
            "content_type": "myth-bust",
            "pillar": [
              "open",
              "social"
            ],
            "tier": 1,
            "tone": "playful-witty",
            "audience": [
              "general"
            ],
            "channel": [
              "social-media"
            ],
            "reading_level": "grade-6-8"
          }
        },
        {
          "id": "wildcard",
          "category": "wildcard",
          "title": "Read the × before the $.",
          "rationale": "The multiplication sign takes top billing over a promotional dollar figure. A large equation exposes the wagering requirement, followed by two concrete terms to check.",
          "caption": "A bonus has more than one number. Example: a $50 bonus with a 20× rule on the bonus alone means $1,000 in qualifying bets before bonus withdrawal. Check which games count and when the offer expires. Read the terms before opting in.",
          "alt": "Playbook bonus decoder card on emerald. Headline: Read the × before the $. The stated example is a 20-times wagering rule that applies to the bonus only. A navy equation panel reads $50 bonus multiplied by 20 multiplier equals $1,000 in qualifying bets required before bonus withdrawal. Text: Check which games count and when the offer expires. Action: Read the terms before opting in. A protected navy footer displays free support and age information from the brand configuration.",
          "sources": [
            {
              "path": "messaging/myth-busting.md",
              "section": "Myth 20: A Bonus Is Free Money",
              "note": "The entry defines wagering requirements as a multiplier applied to the bonus and discusses game restrictions and expiry. This original example uses $50 × 20 = $1,000 in qualifying bets. The bonus-only basis is explicitly stated on the card; no expected-loss or withdrawal guarantee is claimed."
            },
            {
              "path": "messaging/core-messages.md",
              "section": "Promotional disclaimers",
              "note": "RC-9 supports reading the full terms before opting in."
            }
          ],
          "tags": {
            "content_type": "quick-reference",
            "pillar": [
              "open"
            ],
            "tier": 1,
            "tone": "playful-witty",
            "audience": [
              "general"
            ],
            "channel": [
              "social-media"
            ],
            "reading_level": "grade-6-8"
          }
        }
      ],
      "notes": "Illustrative English comparison masters, not operator-specific offers or active controls. Bonus rules and eligible game contributions vary; the example specifies a bonus-only multiplier and qualifying bets. Slot artwork is an invented non-winning example, not a universal paytable. Support and age placeholders resolve from the common brand configuration, and need the intended operator/jurisdiction configuration before public use. All claims use the common packet and simple arithmetic; no external research or raster image assets were used.",
      "validation": [
        {
          "id": "sports",
          "width": 1080,
          "height": 1350,
          "minFontSize": 42,
          "textCount": 18,
          "issues": []
        },
        {
          "id": "myth",
          "width": 1080,
          "height": 1350,
          "minFontSize": 42,
          "textCount": 13,
          "issues": []
        },
        {
          "id": "wildcard",
          "width": 1080,
          "height": 1350,
          "minFontSize": 42,
          "textCount": 20,
          "issues": []
        }
      ]
    },
    {
      "folder": "sol",
      "label": "GPT-5.6 Sol",
      "model": "gpt-5.6-sol",
      "reasoning": "high",
      "blindLabel": "Studio B",
      "concepts": [
        {
          "id": "sports",
          "category": "sports",
          "title": "Half right. Still down.",
          "rationale": "A scoreboard makes the hidden cost of a 50% record at −110 instantly visible. The familiar win-loss frame turns vig math into one clean, memorable result.",
          "caption": "Win half your bets at −110 and you are still down. Ten equal bets make the vig easy to see: +$500 from five wins, −$550 from five losses. Read the line before you call it even.",
          "alt": "Playbook sports-math card titled Half right. Still down. A navy scoreboard shows ten equal bets at minus 110: five wins produce 500 dollars in profit, five losses cost 550 dollars, leaving a season total of minus 50 dollars. The action line reads Read the line. Price the vig.",
          "sources": [
            {
              "path": "how-to-play/sports-betting.md",
              "section": "Break-even win rates",
              "note": "The guide states that −110 odds require a 52.4% break-even win rate. Visible arithmetic assumes ten equal $110 bets: 5 × $100 profit = $500 and 5 × $110 loss = $550, for a $50 net loss."
            }
          ],
          "tags": {
            "content_type": "quick-reference",
            "pillar": [
              "open"
            ],
            "tier": 1,
            "tone": "confident-informative",
            "audience": [
              "sports-bettors"
            ],
            "channel": [
              "social-media"
            ],
            "reading_level": "grade-6-8"
          }
        },
        {
          "id": "myth",
          "category": "myth",
          "title": "95% RTP is not 95 winning spins.",
          "rationale": "An editorial equation separates two numbers players can easily confuse: money returned over time and winning-spin frequency. The bold not-equal line makes the correction readable before the explanation.",
          "caption": "A 95% RTP does not promise 95 winning spins out of 100. RTP tracks the share of money returned across all play over time. One session can land anywhere. Check the number—and what it actually measures.",
          "alt": "Bright emerald Playbook myth card titled 95 percent RTP is not 95 winning spins. A white proof panel states that 95 percent equals long-run money returned and does not equal 95 winning spins out of 100. A note says the example applies across all play over time and one session can land anywhere.",
          "sources": [
            {
              "path": "how-to-play/slots.md",
              "section": "House edge and RTP",
              "note": "The guide defines RTP as the percentage of all money wagered that a machine pays back over its lifetime; a 95% RTP leaves a 5% house edge."
            },
            {
              "path": "how-to-play/slots.md",
              "section": "Question 2",
              "note": "The guide explicitly distinguishes 95% RTP from winning 95% of spins and from retaining 95% of a starting balance in one session."
            }
          ],
          "tags": {
            "content_type": "myth-bust",
            "pillar": [
              "open",
              "social"
            ],
            "tier": 1,
            "tone": "playful-witty",
            "audience": [
              "general"
            ],
            "channel": [
              "social-media"
            ],
            "reading_level": "grade-6-8"
          }
        },
        {
          "id": "wildcard",
          "category": "wildcard",
          "title": "Small bet. Fast clock.",
          "rationale": "A tempo ladder shows how a small per-spin amount accumulates at common slot speed. The arithmetic is the artwork, giving players a quick way to connect pace with their entertainment budget.",
          "caption": "Fifty cents feels small. At an example pace of one spin every three seconds, it becomes 20 spins and $10 wagered each minute—$600 wagered in an hour. Pick your pace and set your entertainment budget before the reels start.",
          "alt": "Orange Playbook pace-check card titled Small bet. Fast clock. A navy calculation board shows 50 cents each spin times 20 spins per minute equals 10 dollars wagered per minute. A second line shows 10 dollars times 60 minutes equals 600 dollars wagered per hour. The action line reads Pick your pace. Set your budget.",
          "sources": [
            {
              "path": "how-to-play/slots.md",
              "section": "Tips for informed play",
              "note": "The guide gives the same visible assumption and result: a $0.50 bet every 3 seconds equals $600 wagered per hour. Arithmetic: 60 ÷ 3 = 20 spins per minute; 20 × $0.50 = $10 per minute; $10 × 60 = $600 per hour."
            }
          ],
          "tags": {
            "content_type": "quick-reference",
            "pillar": [
              "open",
              "tools"
            ],
            "tier": 1,
            "tone": "confident-informative",
            "audience": [
              "general"
            ],
            "channel": [
              "social-media"
            ],
            "reading_level": "grade-6-8"
          }
        }
      ],
      "notes": "The sports example assumes equal $110 stakes at −110. The myth uses 95% as an illustrative slot RTP and does not predict a single session. The wildcard shows amount wagered, not expected loss or money remaining.",
      "validation": [
        {
          "id": "sports",
          "width": 1080,
          "height": 1350,
          "minFontSize": 42,
          "textCount": 15,
          "issues": []
        },
        {
          "id": "myth",
          "width": 1080,
          "height": 1350,
          "minFontSize": 42,
          "textCount": 15,
          "issues": []
        },
        {
          "id": "wildcard",
          "width": 1080,
          "height": 1350,
          "minFontSize": 42,
          "textCount": 19,
          "issues": []
        }
      ]
    },
    {
      "folder": "terra",
      "label": "GPT-5.6 Terra",
      "model": "gpt-5.6-terra",
      "reasoning": "high",
      "blindLabel": "Studio C",
      "concepts": [
        {
          "id": "sports",
          "category": "sports",
          "title": "Every Leg Has to Land",
          "rationale": "A parlay ticket turns the all-or-nothing rule into a quick visual read. Its one-in-eight example states the independent 50/50-pick assumption used for the arithmetic.",
          "caption": "A parlay is one bet with several picks. Every leg has to win. With three independent 50/50 picks, that is one chance in eight. Read the whole ticket before the game starts.",
          "alt": "A Playbook social card with a three-pick parlay ticket. It says every leg has to land, every pick must win, and three independent picks with a true 50/50 chance each produce a one-in-eight chance that all three win.",
          "sources": [
            {
              "path": "how-to-play/sports-betting.md",
              "section": "Parlays",
              "note": "Supports that all picks must win. The card separately states its 0.5 × 0.5 × 0.5 = 1 in 8 independent-pick arithmetic assumption; it does not derive probability from a quoted price."
            }
          ],
          "tags": {
            "content_type": "quick-reference",
            "pillar": [
              "open"
            ],
            "tier": 1,
            "tone": "confident-informative",
            "audience": [
              "sports-bettors"
            ],
            "channel": [
              "social-media"
            ],
            "reading_level": "grade-6-8"
          }
        },
        {
          "id": "myth",
          "category": "myth",
          "title": "The Slot Does Not Have a Memory",
          "rationale": "A fading sequence of old spins makes the independence of the next result immediate. The visual gives the myth a concrete answer without scolding the player.",
          "caption": "A slot cannot be due. Each spin is independent, so past results cannot change the next one.",
          "alt": "A dark Playbook myth card reads The slot does not have a memory. Seven faded past spin markers sit above a bright label stating Next spin: same odds.",
          "sources": [
            {
              "path": "messaging/myth-busting.md",
              "section": "Myth 2: Due for a Win",
              "note": "Supports that each spin is generated independently and that a machine with 200 prior spins has the same odds on spin 201."
            }
          ],
          "tags": {
            "content_type": "myth-bust",
            "pillar": [
              "open"
            ],
            "tier": 1,
            "tone": "playful-witty",
            "audience": [
              "general"
            ],
            "channel": [
              "social-media"
            ],
            "reading_level": "grade-6-8"
          }
        },
        {
          "id": "wildcard",
          "category": "wildcard",
          "title": "RTP Is the Long Game",
          "rationale": "A receipt-style calculation separates return to player from a session outcome. It turns the 95 percent RTP example into clear, visible long-run arithmetic.",
          "caption": "A 95% RTP describes a long-run average, not a promise for one session. The paytable is the place to start.",
          "alt": "A Playbook social card uses a receipt layout to explain a 95 percent slot return to player. It shows 100 dollars wagered over time, approximately 95 dollars paid back, and approximately 5 dollars as the house edge.",
          "sources": [
            {
              "path": "how-to-play/slots.md",
              "section": "What this means for your wallet",
              "note": "Supports the 95% RTP and 5% house-edge example: for every $100 bet over time, about $5 is lost on average; a session may vary."
            }
          ],
          "tags": {
            "content_type": "quick-reference",
            "pillar": [
              "open"
            ],
            "tier": 1,
            "tone": "confident-informative",
            "audience": [
              "general"
            ],
            "channel": [
              "social-media"
            ],
            "reading_level": "grade-6-8"
          }
        }
      ],
      "notes": "Sports probability uses three independent picks, each with a true 50/50 chance: 0.5³ = 1 in 8. RTP is a long-run average and does not predict an individual session.",
      "validation": [
        {
          "id": "sports",
          "width": 1080,
          "height": 1350,
          "minFontSize": 42,
          "textCount": 15,
          "issues": []
        },
        {
          "id": "myth",
          "width": 1080,
          "height": 1350,
          "minFontSize": 42,
          "textCount": 17,
          "issues": []
        },
        {
          "id": "wildcard",
          "width": 1080,
          "height": 1350,
          "minFontSize": 42,
          "textCount": 18,
          "issues": []
        }
      ]
    },
    {
      "folder": "gpt-53-spark",
      "label": "GPT-5.3 Codex Spark",
      "model": "gpt-5.3-codex-spark",
      "reasoning": "high",
      "blindLabel": "Studio D",
      "imageInspection": "Agent reported image inspection unavailable; coordinator inspected outputs.",
      "concepts": [
        {
          "id": "sports",
          "category": "sports",
          "title": "One miss, no rescue.",
          "rationale": "The card turns parlay math into one visible equation: two required outcomes mean one miss ends the ticket, which is the key cost mechanism many players miss when they compare payouts first.",
          "caption": "A two-leg parlay can look attractive, but both independent 50% results must still happen together. The board uses 1/2 × 1/2 = 1/4, so about 1 in 4 tickets lands at that illustrative level. Build your session around entertainment, not a guaranteed combo.",
          "alt": "Playbook sports card on navy background titled One miss, no rescue. A parlay board shows Leg 1 and Leg 2 as independent 50% outcomes, then a formula to 1/4 and a 25% (about 1 in 4) result row. A takeaway says one in four two-leg parlays at this illustrative level. A protected footer shows helpline and age disclaimer placeholders.",
          "sources": [
            {
              "path": "how-to-play/sports-betting.md",
              "section": "Parlays",
              "note": "The table in Parlays lists 2-leg parlay approximate payout around 2.6:1 and approximate probability around 1 in 4; this supports showing multiplication of two leg outcomes into a one-in-four result."
            },
            {
              "path": "how-to-play/sports-betting.md",
              "section": "The vig in practice",
              "note": "The section emphasizes pricing effects on parlays and the compounded margin. This supports the card’s reminder to check the legs before considering payout language."
            }
          ],
          "tags": {
            "content_type": "quick-reference",
            "pillar": [
              "open"
            ],
            "tier": 1,
            "tone": "confident-informative",
            "audience": [
              "sports-bettors"
            ],
            "channel": [
              "social-media"
            ],
            "reading_level": "grade-6-8"
          }
        },
        {
          "id": "myth",
          "category": "myth",
          "title": "Hot streaks are loud, not lucky.",
          "rationale": "A short myth/fact callout contrasts the emotional feel of a streak with the actual independence of slots outcomes, with the key 0% change figure held visually in one line.",
          "caption": "Three wins in a row are memorable, but they do not improve the next spin. Slots are random every pull, and the machine does not remember your last result. One result does not predict the next.",
          "alt": "Playbook myth card on navy background titled Hot streaks are loud, not lucky. A myth/fact label indicates 0% of prior results affecting the next spin. A two-column panel shows Last result, Next spin change at 0%, and Next spin odds listed as same as before, with a takeaway that each spin is independent. A footer with protected placeholders closes the card.",
          "sources": [
            {
              "path": "messaging/myth-busting.md",
              "section": "Myth 1: The Hot Streak",
              "note": "The section states every slot spin is statistically independent and machines do not keep score. The card’s 0% change line directly reflects this claim and the myth line in the article explainer."
            },
            {
              "path": "how-to-play/slots.md",
              "section": "Tips for informed play",
              "note": "The tip section ends with the same principle: each spin is independent and previous outcomes do not affect the next result."
            }
          ],
          "tags": {
            "content_type": "myth-bust",
            "pillar": [
              "open"
            ],
            "tier": 1,
            "tone": "playful-witty",
            "audience": [
              "general"
            ],
            "channel": [
              "social-media"
            ],
            "reading_level": "grade-6-8"
          }
        },
        {
          "id": "wildcard",
          "category": "wildcard",
          "title": "Same edge. Bigger bill.",
          "rationale": "The concept uses a simple 5% edge table to show why bankroll control matters: changing the stake changes money at risk proportionally while the edge percentage stays constant.",
          "caption": "A 5% house edge means expected loss is a percentage of total stake. A game with 95% RTP has about a 5% house edge long-run. On $1, expected loss is about $0.05; on $10, $0.50. Let long-run percentages guide your budget, not a one-spin result.",
          "alt": "Playbook budget-control card on navy background titled Same edge. Bigger bill. A 5% house edge board displays four rows comparing $1, $10, $100, and $1,000 stakes/wagers. The values show expected long-run losses of $0.05, $0.50, $5, and $50, reinforcing that the house-edge percentage stays fixed while dollar amounts scale. The action line says House edge fixed. Dollar amounts scale. Protected helpline and age placeholders appear in the footer.",
          "sources": [
            {
              "path": "how-to-play/slots.md",
              "section": "House edge and RTP",
              "note": "The section defines house edge as the percentage of total wagers kept by the game and gives typical RTP ranges. 95% RTP corresponds to 5% house edge, which is used for the expected-loss examples."
            },
            {
              "path": "messaging/myth-busting.md",
              "section": "Myth 6: Higher Bets Improve Your Odds",
              "note": "The myth entry explicitly states house-edge percentage is fixed across stake sizes and larger bets scale both wins and losses. The table applies that rule to an illustrative 95% RTP (5% edge) example."
            }
          ],
          "tags": {
            "content_type": "quick-reference",
            "pillar": [
              "open",
              "tools"
            ],
            "tier": 1,
            "tone": "confident-informative",
            "audience": [
              "general"
            ],
            "channel": [
              "social-media"
            ],
            "reading_level": "grade-6-8"
          }
        }
      ],
      "notes": "Sports concept shows a two-leg two independent 50% assumption explicitly; 1 in 4 is an outcome-level illustration and does not claim a guaranteed short-term hit rate. Myth concept uses independent-spin wording from cited references. Wildcard values are long-run expected-loss illustrations using 95% RTP / 5% house-edge and do not guarantee any single-spin result.",
      "validation": [
        {
          "id": "sports",
          "width": 1080,
          "height": 1350,
          "minFontSize": 42,
          "textCount": 18,
          "issues": []
        },
        {
          "id": "myth",
          "width": 1080,
          "height": 1350,
          "minFontSize": 42,
          "textCount": 16,
          "issues": []
        },
        {
          "id": "wildcard",
          "width": 1080,
          "height": 1350,
          "minFontSize": 42,
          "textCount": 21,
          "issues": []
        }
      ]
    },
    {
      "folder": "gpt-55",
      "label": "GPT-5.5",
      "model": "gpt-5.5",
      "reasoning": "high",
      "blindLabel": "Studio E",
      "imageInspection": "Agent and coordinator inspected outputs.",
      "concepts": [
        {
          "id": "sports",
          "category": "sports",
          "title": "The live line is already moving.",
          "rationale": "A live odds board turns in-play betting into a speed comparison: the sportsbook reprices first, then the player taps. The concept focuses on price awareness rather than promising an advantage.",
          "caption": "Live betting feels like reacting in the moment. The line is already moving. Sportsbooks reprice live odds in milliseconds, and in-play vig is often wider than pre-game. Check the price before you chase the moment.",
          "alt": "Playbook sports math card on navy. Headline: The live line is already moving. An example live betting board shows Example: before at minus 110, Example: after at minus 125, and Your tap next. A bright panel says algorithms reprice live odds in milliseconds. Body text says watching the game feels like an edge, but the sportsbook is watching faster. Action line says check the price before you chase the moment. A protected footer displays free support and age information from the brand configuration.",
          "sources": [
            {
              "path": "how-to-play/sports-betting.md",
              "section": "In-play (live betting)",
              "note": "The section says live odds update in real time, odds change rapidly, algorithms process data faster than humans, and in-play vig is often wider than pre-game. The displayed odds are illustrative movement, not a claim about a specific game."
            },
            {
              "path": "messaging/myth-busting.md",
              "section": "Myth 14: In-Play Betting Gives You an Edge",
              "note": "This myth supports the milliseconds wording and the point that by the time a player reacts, the line has usually moved."
            }
          ],
          "tags": {
            "content_type": "quick-reference",
            "pillar": [
              "open"
            ],
            "tier": 1,
            "tone": "confident-informative",
            "audience": [
              "sports-bettors"
            ],
            "channel": [
              "social-media"
            ],
            "reading_level": "grade-6-8"
          }
        },
        {
          "id": "myth",
          "category": "myth",
          "title": "Bigger spin. Same percentage.",
          "rationale": "Two side-by-side wager sizes show that the house edge percentage stays the same when the game settings and paytable are unchanged, while the dollar cost scales. The visual makes the myth correction concrete without telling players how much to bet.",
          "caption": "Bet size changes the volume, not the house edge, when the game settings and paytable stay the same. This example uses a 5% edge: 5 cents per $1, or $5 per $100. Bigger bets mean bigger swings, not better odds.",
          "alt": "Playbook myth versus math card on a light background. Headline: Bigger spin. Same percentage. Two slot bet examples for the same game settings and paytable show an example one dollar spin with a five percent edge and five cents in play cost over time, beside the same game at a one hundred dollar spin with the same five percent edge and five dollars in play cost over time. Body text says same game settings, same paytable: bet size scales dollars, not the edge. Action line says five percent example and pick your bet for budget, not better odds. A protected footer displays free support and age information from the brand configuration.",
          "sources": [
            {
              "path": "messaging/myth-busting.md",
              "section": "Myth 6: Higher Bets Improve Your Odds",
              "note": "The social card and explainer state that the house edge is a percentage and that bigger bets scale dollar outcomes rather than improving odds. The card makes the 5% assumption visible and uses the myth's arithmetic: 5 cents per $1 or $5 per $100."
            },
            {
              "path": "how-to-play/slots.md",
              "section": "Bet types",
              "note": "The key point says betting more per spin does not improve odds; bigger bets mean bigger potential wins and bigger potential losses at the same rate. The card qualifies this as the same game settings and paytable."
            }
          ],
          "tags": {
            "content_type": "myth-bust",
            "pillar": [
              "open",
              "social"
            ],
            "tier": 1,
            "tone": "playful-witty",
            "audience": [
              "general"
            ],
            "channel": [
              "social-media"
            ],
            "reading_level": "grade-6-8"
          }
        },
        {
          "id": "wildcard",
          "category": "wildcard",
          "title": "The small spin can move fast.",
          "rationale": "A pace meter and oversized equation make slot speed visible. The idea reframes a low per-spin amount as throughput, helping players set a budget before play starts.",
          "caption": "Small spins can add up fast. Example: $0.50 every 3 seconds is 20 spins per minute. Over an hour, that is $600 total wagered, not $600 necessarily lost. Set the budget before the reels get chatty.",
          "alt": "Playbook budget math card on emerald. Headline: The small spin can move fast. A dark pace meter says fifty cents every three seconds. The equation panel reads fifty cents times twenty per minute times sixty minutes equals six hundred dollars per hour, with a note that this is total wagered, not money lost. Action line says set your budget before the reels get chatty. A protected footer displays free support and age information from the brand configuration.",
          "sources": [
            {
              "path": "how-to-play/slots.md",
              "section": "Tips for informed play",
              "note": "Tip 4 states that a $0.50 bet every 3 seconds adds up to $600 per hour. The card shows the arithmetic: one spin every 3 seconds equals 20 spins per minute; $0.50 x 20 x 60 = $600 total wagered, not money lost."
            },
            {
              "path": "messaging/core-messages.md",
              "section": "Tools — Features that work for you",
              "note": "The tools messages support framing budgets and limits as player-controlled features. The card uses an action line about setting a budget without presenting an active account control."
            }
          ],
          "tags": {
            "content_type": "quick-reference",
            "pillar": [
              "open",
              "tools"
            ],
            "tier": 1,
            "tone": "confident-informative",
            "audience": [
              "general"
            ],
            "channel": [
              "social-media"
            ],
            "reading_level": "grade-6-8"
          }
        }
      ],
      "notes": "Illustrative English Tier 1 comparison masters only. Live odds and slot examples vary by product and jurisdiction, so operator-specific releases should verify their own lines, RTP, game pace, and support configuration. The odds movement in the sports card is illustrative; no external research or raster image assets were used.",
      "validation": [
        {
          "id": "sports",
          "width": 1080,
          "height": 1350,
          "minFontSize": 42,
          "textCount": 16,
          "issues": []
        },
        {
          "id": "myth",
          "width": 1080,
          "height": 1350,
          "minFontSize": 42,
          "textCount": 15,
          "issues": []
        },
        {
          "id": "wildcard",
          "width": 1080,
          "height": 1350,
          "minFontSize": 42,
          "textCount": 16,
          "issues": []
        }
      ]
    }
  ],
  "categories": [
    {
      "id": "sports",
      "label": "Sports betting",
      "description": "Explain something about how a sports bet works."
    },
    {
      "id": "myth",
      "label": "Gambling myth",
      "description": "Give a familiar gambling belief a fresh fact-based treatment."
    },
    {
      "id": "wildcard",
      "label": "Agent’s choice",
      "description": "Explore another angle on entertainment literacy."
    }
  ],
  "method": "Five agents received fresh contexts, different model overrides, identical high reasoning requests, and the same dispatch text except for assigned output folder. Each was required to read the frozen common brief and 19 input files, and forbidden to inspect other participant outputs. Each authored and revised its own three concepts using the common renderer. Model-specific coordinator feedback and unequal image-inspection access make these revised pilot examples unsuitable for a controlled model ranking. The original three and added two were dispatched in separate batches. No scores or winners are assigned.",
  "status": "revised-pilot-unscored",
  "defaultSelection": [
    "gpt-53-spark",
    "gpt-55"
  ],
  "unavailable": [
    {
      "model": "gpt-5.4",
      "status": "unavailable-not-scored",
      "evidence": [
        "Subagent interface rejected unknown model gpt-5.4.",
        "Codex CLI 0.146.1 read-only availability probe: The 'gpt-5.4' model is not supported when using Codex with a ChatGPT account."
      ],
      "date": "2026-09-04"
    }
  ],
  "modelIdProvenance": "Model IDs and high reasoning are requested dispatch overrides accepted by the agent interface, not independent backend snapshot or compute telemetry.",
  "inputs": {
    "baselineCommit": "d18952be5a70ff556f9e1c5b52faa33b45efd254",
    "briefSha256": "595e0f7c30620831c991c63bf3ac034f917afbc0c0df5e51f11dd94197780a4d",
    "references": [
      {
        "path": "AGENTS.md",
        "sha256": "2c6d34e3eaba341b493f03b79a1141424162fc171714164bf1d126ac19c75665"
      },
      {
        "path": ".claude/commands/brand-create.md",
        "sha256": "f7eb98537eb9ce408bb8e2bb3e4ab6b219d650c14837cd9f7fe264e64c840fe9"
      },
      {
        "path": "_brand.yml",
        "sha256": "1b3f1ff766bef0d2b3382241d34efd74c4d110f696a453235023751618d10d5c"
      },
      {
        "path": "_taxonomy.yml",
        "sha256": "3a7b4706c9e53bcae41e341d74825a8c986d268d2269a03cb0e1c9c4147bbd08"
      },
      {
        "path": "brand-book/02-brand-personality.md",
        "sha256": "51b22ffa656e8a564e6ce7becb4552d94aa86ee9a7ff2753eca70ec66e253b76"
      },
      {
        "path": "brand-book/03-visual-identity.md",
        "sha256": "ff5ff681e25516f5a40b0c801cb8d4fcc618eda9431959d30be32b403b5bfa84"
      },
      {
        "path": "brand-book/04-voice-and-tone.md",
        "sha256": "06dec15af7e097c0ecdc1c5bc3e756d216e23a93afd44fdf73ac27648a42307c"
      },
      {
        "path": "brand-book/05-messaging-framework.md",
        "sha256": "3b04aa5f9fd4a7f3eeeec6682edba565e07746e451b825eff309d42d4f11431f"
      },
      {
        "path": "messaging/stigma-free-language.md",
        "sha256": "d3c232dc84b91c4acede4d78f8c2ca36e44111af946953aa30fd0851897eb092"
      },
      {
        "path": "messaging/core-messages.md",
        "sha256": "d4c28979dcc418a479e6a30a301a1be051fb03d66743ec99a2944a1d4a6534df"
      },
      {
        "path": "messaging/myth-busting.md",
        "sha256": "8c0d0d8ddfa603d493d85ba2bdb4f544365226557c1361f65847f42ff74fd0c2"
      },
      {
        "path": "how-to-play/sports-betting.md",
        "sha256": "e6255eb959946f9839cd08445d7383a17348a037f5fa9e8acaa9a8f5985064be"
      },
      {
        "path": "how-to-play/slots.md",
        "sha256": "a38977f52fb911cca605467091101e59d2c90394e8704eb8597cdaf43dd9cefd"
      },
      {
        "path": "collateral/render/card-15a-point-spread.html",
        "sha256": "b04af108d66ea24ad212c34ec3f26ca62dcdf0df05cc23cc34b591ae16f395d6"
      },
      {
        "path": "collateral/render/card-13a-its-due.html",
        "sha256": "2d1b27b17b6e6c1f06303998e05a4048b92f493b60c708d46411351c5ba8591b"
      },
      {
        "path": "collateral/render/card-20b-pick-your-pause.html",
        "sha256": "5ef7f4b650cec2d07a6566c714221a7b310c2997b9a63468e4c01bfb0e032593"
      },
      {
        "path": "collateral/render/concept-20.css",
        "sha256": "f38556dc281826d01e3f0d6bb46490ebbf46357d167dfdab0a652851473e8219"
      },
      {
        "path": "collateral/render/layout-system.css",
        "sha256": "3bf631b004124a5fd7a01dd784342b105760d42d0887d7f987051f84958600b0"
      },
      {
        "path": "collateral/render/model-comparison/fonts.css",
        "sha256": "beaf18d19bfbaaefccdcc2c7cfe57b120a83a2a83d0971c24eb3bc2d41cb9460"
      }
    ]
  }
};
