const {directions,entries}=window.STYLE_STUDIES;
const params=new URLSearchParams(location.search);
let application=['odds','lifestyle','support'].includes(params.get('application'))?params.get('application'):'odds';
const selected=new Set((params.get('compare')||'').split(',').filter(id=>directions.some(d=>d.id===id)));
let focused=selected.size>=2;
const grid=document.getElementById('directions'),compare=document.getElementById('compare'),showAll=document.getElementById('show-all'),status=document.getElementById('view-status');
const viewer=document.getElementById('viewer');let lastPreview=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function updateControls(){compare.disabled=selected.size<2;compare.textContent=selected.size?'Compare selected ('+selected.size+')':'Compare selected';showAll.hidden=!focused;status.textContent=focused?'Showing '+selected.size+' directions. Select a card to enlarge the finished specimen.':'Select two directions for a closer comparison.';document.querySelectorAll('[data-kind]').forEach(b=>{const active=b.dataset.kind===application;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});}
function render(){
 grid.className='direction-grid'+(focused?' focused':'')+(application==='support'?' support-view':'');
 grid.innerHTML=directions.filter(d=>!focused||selected.has(d.id)).map(d=>{const e=entries.find(x=>x.direction===d.id&&x.kind===application);return `<article class="direction-card" data-direction="${d.id}"><div class="direction-heading"><h2>${esc(d.name)}</h2><label class="compare-check"><input type="checkbox" data-select="${d.id}" ${selected.has(d.id)?'checked':''}>Compare</label></div><p class="position">${esc(d.position)}</p><button class="preview-button" data-preview="${e.id}" aria-label="Enlarge ${esc(e.title)}"><img src="${e.png}" alt="${esc(e.title)}" width="${e.width}" height="${e.height}"></button><p class="preview-caption"><span>${e.width} × ${e.height}</span><span>Click to enlarge ↗</span></p><div class="palette" aria-label="${esc(d.palette.map(p=>p.join(' ')).join(', '))}">${d.palette.map(([n,c])=>`<span style="background:${c}" title="${esc(n+' '+c)}"></span>`).join('')}</div><p class="direction-description">${esc(d.description)}</p><p class="type-note">${esc(d.type)}</p><details><summary>Where this direction works</summary><p>${esc(d.fit)}</p><p>${esc(d.note)}</p><p>${esc(d.shape)}</p><ul>${d.palette.map(([n,c])=>`<li>${esc(n)} / ${c}</li>`).join('')}</ul><a href="${e.html}">HTML master ↗</a></details></article>`;}).join('');
 updateControls();const url=new URL(location.href);url.searchParams.set('application',application);if(focused)url.searchParams.set('compare',[...selected].join(','));else url.searchParams.delete('compare');history.replaceState(null,'',url);
}
document.querySelectorAll('[data-kind]').forEach(b=>b.addEventListener('click',()=>{application=b.dataset.kind;render();}));
grid.addEventListener('change',e=>{if(!e.target.matches('[data-select]'))return;const id=e.target.dataset.select;e.target.checked?selected.add(id):selected.delete(id);if(focused){if(selected.size<2)focused=false;render();}else updateControls();});
compare.addEventListener('click',()=>{if(selected.size<2)return;focused=true;render();});showAll.addEventListener('click',()=>{focused=false;render();});
grid.addEventListener('click',e=>{const button=e.target.closest('[data-preview]');if(!button)return;lastPreview=button;const item=entries.find(x=>x.id===button.dataset.preview);document.getElementById('viewer-title').textContent=item.title;const img=document.getElementById('viewer-image');img.src=item.png;img.alt=item.title;document.getElementById('full-image').href=item.png;document.getElementById('source-link').href=item.html;viewer.showModal();});
document.getElementById('close-viewer').addEventListener('click',()=>viewer.close());viewer.addEventListener('close',()=>lastPreview?.focus());viewer.addEventListener('click',e=>{if(e.target===viewer){const r=viewer.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)viewer.close();}});
render();
