export function review(manifest,reports,selection){
  const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Playbook · Background & CSS directions</title><link rel="stylesheet" href="review.css"></head>
<body>
<header class="intro"><a class="back" href="../text-polish/index.html">← The everyday Playbook</a><div class="masthead"><span class="wordmark">Playbook</span><span>Design study / 06</span></div><p class="eyebrow">Backgrounds, type & details</p><h1>One Playbook. Six directions.</h1><p class="lead">Five new CSS directions, alongside the current design. Switch the content to see which treatments hold up across cards, stories and a poster.</p><p class="saved-note">Your previous review is recorded: <strong>21 looks good · 5 needs work.</strong> These new comparisons save separately.</p></header>
<main>
<section class="toolbar" aria-label="Choose the content"><div class="selector"><label for="template">Compare the same content</label><select id="template">${manifest.templates.map(t=>`<option value="${t.id}">${t.format} · ${esc(t.name)}</option>`).join('')}</select></div><div class="stepper"><button id="previous" aria-label="Previous template">←</button><output id="position">1 / ${manifest.templates.length}</output><button id="next" aria-label="Next template">→</button></div><p id="baseline-choice">Previously: needs work</p><button id="export">Export choices ↓</button></section>
<div id="comparisons" aria-live="polite">${manifest.templates.map((t,ti)=>`<section class="template-group" data-template="${t.id}" data-previous="${selection.choices[t.id]}" ${ti?'hidden':''}><h2 class="template-heading">${esc(t.name)} <span>${t.format}</span></h2><div class="design-grid">${manifest.surfaces.map((s,si)=>{const r=reports.find(r=>r.template===t.id&&r.surface===s.id);return `<article class="design" data-id="${r.id}" data-surface="${s.id}"><header><p class="direction-number">${String(si).padStart(2,'0')} / ${s.tag}</p><h3>${s.name}</h3><p class="description">${s.description}</p></header><a class="artwork" href="renders/${r.id}.png" target="_blank" rel="noopener" aria-label="Open full resolution: ${s.name}, ${esc(t.name)}"><img ${ti?'data-src':'src'}="renders/${r.id}.png?v=${r.pngSha256.slice(0,10)}" width="${r.dimensions[0]}" height="${r.dimensions[1]}" alt="${s.name}: ${esc(t.name)}" loading="${ti?'lazy':'eager'}"></a><div class="design-links"><a href="live/${r.id}.html" target="_blank" rel="noopener">Live template ↗</a><span>${r.pixels.join(' × ')}</span></div><div class="choices" role="group" aria-label="Feedback for ${s.name}, ${esc(t.name)}"><button data-choice="favorite" aria-pressed="false">Favorite</button><button data-choice="maybe" aria-pressed="false">Maybe</button><button data-choice="pass" aria-pressed="false">Pass</button></div><output class="save-status" aria-live="polite"></output></article>`;}).join('')}</div></section>`).join('')}</div>
<footer class="endnote"><p>Pick as many as you like. Choices save in this browser; tap a selected choice to clear it. Export a copy to carry them to another browser.</p><p>Every preview is rendered at 2× from live HTML and local fonts. <a href="../render/text-surfaces.css">View the shared CSS ↗</a> · <a href="README.md">Build notes ↗</a></p><output id="export-status" aria-live="polite"></output></footer>
</main><script type="module" src="review.mjs"></script></body></html>\n`;
}
