// Campaign compositions use the same recipe, asset, skin and export contract.
export const campaigns = [
  {id:'campaign-rest',round:4,shortTitle:'The whole evening',theme:'club',layout:'campaign-rest',variants:['after'],title:'04 / Leave room for the rest',format:'Campaign social',series:'Time well spent',headline:'Leave room\nfor the rest.',copy:'Choose a finish time before you play.\nKeep the rest of your night open.',action:'Plan your next pause',visual:'photo',defaultAsset:'room-for-the-rest',artDirection:'room-for-the-rest',rationale:'The photograph fills every edge, with a softer continuous shadow that keeps the scene visible behind the message. Warm light and adult company place gambling within a larger evening.'},
  {id:'campaign-nearmiss',round:4,shortTitle:'The almost-win',theme:'circuit',layout:'campaign-nearmiss',variants:['after'],title:'05 / So close. Same odds.',format:'Campaign social',series:'Myth / Math',headline:'So close.\nSame odds.',copy:'On independent slot spins, a near miss\nnever makes the next win more likely.',action:'See how a spin works',visual:'nearmiss',rationale:'Two cherry symbols and a lemon supply a familiar almost-match. Bold vector silhouettes replace the numbers, giving the same idea a clearer reel identity across all three treatments.'},
  {id:'campaign-zero',round:4,shortTitle:'The extra zero',theme:'club',layout:'campaign-zero',variants:['after'],title:'06 / One extra zero',format:'Campaign social',series:'Inside the odds',headline:'One extra zero.\nDifferent odds.',copy:'House edge on straight-up number bets.\nStandard 35:1 profit payout.',action:'Check which wheel you’re playing',visual:'zero',rationale:'Two precise rings count the pockets. One highlighted pocket becomes two, and the large figures reveal what that small change does to the house edge. The diagram is driven by the actual arithmetic.'},
  {id:'campaign-time',round:4,shortTitle:'Budget your time',theme:'circuit',layout:'campaign-time',variants:['after'],title:'07 / Time is part of the budget',format:'Campaign social',series:'Your play. Your plan.',headline:'Time is part\nof the budget.',copy:'Pick a finish time before you play.\nA reminder can help you keep track.',action:'Choose when to call it a night',visual:'time',rationale:'An oversized precision dial turns a practical time tool into the main graphic. The open arc and pause mark suggest an intentional stopping point, without inventing a session length or a product control.'},
  {id:'campaign-cinema',theme:'club',layout:'campaign-cinema',variants:['after'],title:'01 / The cinematic campaign',format:'Campaign social',series:'Myth / Math',headline:'Luck doesn’t\nkeep score.',copy:'Past losses don’t make the next independent slot spin more likely to win.',action:'Know how the game works',visual:'photo',defaultAsset:'casino-conversation',rationale:'Photography runs to the top and side edges. A continuous shadow carries the message into the image, with no inset frame or separate footer bar.'},
  {id:'campaign-pause',theme:'circuit',layout:'campaign-pause',variants:['after'],title:'02 / The pause campaign',format:'Campaign social',series:'Time well spent',headline:'Your time.\nYour call.',copy:'Choose an end time before you play.\nSet a reminder to check in.',action:'Make room for a pause',visual:'photo',defaultAsset:'evening-pause',rationale:'A portrait composed for a cover: quiet architecture gives the headline room above the people. The photograph reaches every edge; a small SVG pause mark supplies the visual idea.'},
  {id:'campaign-probability',theme:'club',layout:'campaign-probability',variants:['after'],title:'03 / The odds campaign',format:'Campaign social',series:'Inside the odds',headline:'More picks.\nSmaller target.',copy:'Four independent picks, each truly 50/50.\nAll four must win: a 6.25% chance.',action:'Know what you’re combining',visual:'probability',rationale:'Sixteen equal circles and one highlighted outcome make the arithmetic visible. The large figure and full color field extend the clarity of the preferred odds card.'}
];
