import {campaigns} from './campaigns.mjs';
import {brandPresenceTemplate} from './brand-presence.mjs';
import {formatTemplates} from './campaign-formats.mjs';
export const templates=[
  brandPresenceTemplate,
  ...formatTemplates,
  ...campaigns,
  {id:'message-signature',theme:'atelier',layout:'signature',title:'A quiet editorial signature',beforeLabel:'Atelier / separate footer',afterLabel:'Atelier / editorial signature',format:'Lifestyle social',series:'Your time. Your call.',headline:'Even a good night\nhas an end time.',copy:'Choose when to wrap up before you play.\nA reminder can help you keep track.',action:'Pick your pause.',visual:'photo',rationale:'A fine editorial line brings the contact details into the reading flow. The photograph gains room and the age notice remains distinct.'},
  {id:'message-margin',theme:'atelier',layout:'margin',title:'Give the information its own margin',beforeLabel:'Atelier / bottom band',afterLabel:'Atelier / side note',format:'Budget social',series:'A little planning.',headline:'Your night.\nYour number.',copy:'Choose what you’re happy to spend\nbefore the night gets going.',action:'Set your budget.',visual:'plan',rationale:'A broad side note makes the information part of the page architecture. The headline and budget card reflow alongside it; nothing is hidden or rotated.'},
  {id:'message-companion',theme:'club',layout:'companion',title:'An action with support beside it',beforeLabel:'Social Club / separate footer',afterLabel:'Social Club / shared action card',format:'Lifestyle social',series:'Your time. Your call.',headline:'Make time\nfor the rest.',copy:'Set a reminder before you play.\nGive yourself a moment to check in.',action:'Explore time tools.',visual:'photo',rationale:'A cream action card pairs the invitation with a quiet support line. Rounded photography and a generous green field keep the hospitality character.'},
  {id:'message-note',theme:'arcade',layout:'note',title:'Playful page. Straightforward information.',beforeLabel:'Arcade / bottom band',afterLabel:'Arcade / open note',format:'Budget social',series:'Make a little plan.',headline:'Your budget.\nYour call.',copy:'Include gambling in your entertainment budget.\nChoose a limit before you play.',action:'Set your budget.',visual:'plan',rationale:'Bold colour and a tactile planning card carry the playful energy. Contact information sits on a flat, readable note with no game motifs or novelty lettering.'},
  {id:'message-support-first',theme:'quiet',layout:'support-first',title:'Let the contact lead',beforeLabel:'Support / contact at the foot',afterLabel:'Support / contact in the foreground',format:'Support screen',series:'Support',headline:'Here if\nyou need it.',copy:'You can ask a question about gambling before deciding what to do next.',action:'Call support',visual:'support',width:420,height:740,tier:2,rationale:'The phone number moves ahead of the explanation. A light lilac surface, plain language and an obvious action give an adult digital brand a calmer support voice.'},
  {id:'message-open-letter',theme:'warm',layout:'open-letter',title:'A little more like a personal note',beforeLabel:'Support / boxed contact footer',afterLabel:'Support / open invitation',format:'Support screen',series:'Support',headline:'Start with\na question.',copy:'You can talk about gambling without deciding what to do next.',action:'Call support',visual:'support',width:420,height:740,tier:2,rationale:'Warm paper and a single reading edge make support feel like an invitation. Removing the contact box preserves the number, its label and the same action.'},
  {id:'message-banner',theme:'circuit',layout:'banner',title:'Give a small banner room to breathe',beforeLabel:'Circuit / information in the banner',afterLabel:'Circuit / information at the destination',format:'Banner + destination study',width:1080,height:1350,jurisdiction:'united-kingdom',scope:'Great Britain · online-banner scenario',assumption:'The same information moves from the banner into the illustrated destination. IGRG paragraph 46 permits format-specific treatment of online banners; this is not an exception for all social ads. The preview shows a direct support route on the destination.',source:'https://bettingandgamingcouncil.com/uploads/IGRG_2026-03-03-133712_dwft.pdf',sourceTitle:'IGRG code, paragraph 46',rationale:'Two connected surfaces are shown together. The banner keeps one short invitation; the destination provides an immediately visible support route. Both views retain the same words. The miniature browser is a static layout specimen.'},
  {id:'message-protected',theme:'club',layout:'protected',title:'Build the composition around the message',beforeLabel:'Wagering / protected bottom panel',afterLabel:'Wagering / inset message panel',format:'Wagering social study',series:'A little planning.',headline:'Your budget.\nYour call.',copy:'Decide what you can spend\nbefore you place a bet.',action:'Explore deposit limits.',visual:'plan',jurisdiction:'australia',scope:'Australia · online-wagering social scenario',assumption:'Both versions keep the same black-on-white tagline and support CTA. This studies panel placement, not exemption. Operator, state/territory, placement and any additional disclosure requirements still need review.',source:'https://www.dss.gov.au/system/files/resources/consistent-gambling-messaging-implementation-factsheet_0.pdf',sourceTitle:'DSS social-media messaging guidance',rationale:'The warning becomes a deliberate white panel within the composition. Its type stays straightforward; the surrounding green and cream design supplies the brand expression.'}
];
