/* css-export.js — Generates the self-contained brand-inject.css.

   Emits BOTH variable vocabularies:
   - Canonical names used by lib/generate-inject-css.mjs and every template
     in collateral/render/ (--pb-text-*, --pb-leading-*, --pb-template-text-scale)
   - Legacy names the configurator historically emitted (--pb-scale-*,
     --pb-line-height-*), kept so existing consumers of downloaded files
     don't break.

   The /*! PLAYBOOK_META {...} *​/ JSON block must stay first in the file —
   the RG website's "Try your brand" uploader parses it. */

import { appState } from './state.js';
import { lighten, darken } from './color-utils.js';

function val(id, fallback = '') {
  const el = document.getElementById(id);
  return el && el.value ? el.value : fallback;
}

function num(id, fallback) {
  const v = parseFloat(val(id));
  return Number.isFinite(v) ? v : fallback;
}

export function getTypeScale() {
  return {
    display: num('scaleDisplay', 3.0),
    h1: num('scaleH1', 2.5),
    h2: num('scaleH2', 2.0),
    h3: num('scaleH3', 1.5),
    h4: num('scaleH4', 1.25),
    bodyLarge: num('scaleBodyLarge', 1.125),
    body: num('scaleBody', 1.0),
    small: num('scaleSmall', 0.875),
    caption: num('scaleCaption', 0.75),
    lhHeading: num('lhHeading', 1.2),
    lhBody: num('lhBody', 1.6),
    lhTight: num('lhTight', 1.3),
  };
}

function customFontFaceBlock() {
  if (!appState.customFontDataUrl || !appState.customFontName) return '';
  let fmt = 'woff2';
  const url = appState.customFontDataUrl;
  if (url.indexOf('data:font/woff2') === 0) fmt = 'woff2';
  else if (url.indexOf('data:font/woff') === 0) fmt = 'woff';
  else if (url.indexOf('data:font/ttf') === 0) fmt = 'truetype';
  else if (url.indexOf('data:font/otf') === 0) fmt = 'opentype';
  return `/* Custom font (embedded as data URL — no sidecar file needed) */
@font-face {
  font-family: '${appState.customFontName}';
  src: url('${url}') format('${fmt}');
  font-display: swap;
}

`;
}

/* The :root variables + font-face + logo rules, shared by the downloadable
   file and the template-gallery iframes. */
export function generateVariablesBlock() {
  const primary = val('colorPrimary', '#1B2838');
  const secondary = val('colorSecondary', '#00D4AA');
  const accent = val('colorAccent', '#FF6B35');
  const primaryLight = val('colorFooterBar', lighten(primary, 0.15));
  const primaryDark = darken(primary, 0.3);
  const secondaryLight = lighten(secondary, 0.15);
  const secondaryDark = darken(secondary, 0.2);
  const accentLight = lighten(accent, 0.15);
  const accentDark = darken(accent, 0.15);
  const headingFont = val('fontHeading', 'Inter');
  const bodyFont = val('fontBody', 'Source Sans 3');
  const monoFont = val('fontMono', 'Source Code Pro');
  const ts = getTypeScale();
  const gradEl = document.getElementById('allowGradients');
  const allowGradients = gradEl ? gradEl.checked : true;

  return customFontFaceBlock() + `/* brand-inject.css — Generated by the Playbook Brand Configurator */
:root {
  /* Colors */
  --pb-color-primary: ${primary};
  --pb-color-primary-light: ${primaryLight};
  --pb-color-primary-dark: ${primaryDark};
  --pb-color-secondary: ${secondary};
  --pb-color-secondary-light: ${secondaryLight};
  --pb-color-secondary-dark: ${secondaryDark};
  --pb-color-accent: ${accent};
  --pb-color-accent-light: ${accentLight};
  --pb-color-accent-dark: ${accentDark};
  --pb-color-neutral-900: ${val('colorN900', '#1A1A2E')};
  --pb-color-neutral-700: ${val('colorN700', '#3D3D5C')};
  --pb-color-neutral-500: ${val('colorN500', '#6B6B8A')};
  --pb-color-neutral-300: ${val('colorN300', '#A8A8C0')};
  --pb-color-neutral-200: ${val('colorN200', '#C8C8D8')};
  --pb-color-neutral-100: ${val('colorN100', '#E8E8F0')};
  --pb-color-neutral-50: ${val('colorN50', '#F5F5FA')};
  --pb-color-success: ${val('colorSuccess', '#00C853')};
  --pb-color-warning: ${val('colorWarning', '#FFB300')};
  --pb-color-danger: ${val('colorDanger', '#FF3D00')};
  --pb-color-info: #2979FF;
  --pb-color-white: #FFFFFF;
  --pb-color-black: #111111;

  /* Fonts */
  --pb-font-heading: '${headingFont}', system-ui, -apple-system, sans-serif;
  --pb-font-body: '${bodyFont}', system-ui, sans-serif;
  --pb-font-mono: '${monoFont}', monospace;

  /* Type Scale (canonical names used by all templates) */
  --pb-text-display: ${ts.display}rem;
  --pb-text-h1: ${ts.h1}rem;
  --pb-text-h2: ${ts.h2}rem;
  --pb-text-h3: ${ts.h3}rem;
  --pb-text-h4: ${ts.h4}rem;
  --pb-text-body-lg: ${ts.bodyLarge}rem;
  --pb-text-body: ${ts.body}rem;
  --pb-text-small: ${ts.small}rem;
  --pb-text-caption: ${ts.caption}rem;

  /* Line Heights (canonical) */
  --pb-leading-heading: ${ts.lhHeading};
  --pb-leading-body: ${ts.lhBody};
  --pb-leading-tight: ${ts.lhTight};

  /* Template scale multiplier (body scale relative to the 1.0rem default) */
  --pb-template-text-scale: ${Math.round((ts.body / 1.0) * 1000) / 1000};

  /* Legacy aliases (older consumers of configurator-generated CSS) */
  --pb-scale-display: ${ts.display}rem;
  --pb-scale-h1: ${ts.h1}rem;
  --pb-scale-h2: ${ts.h2}rem;
  --pb-scale-h3: ${ts.h3}rem;
  --pb-scale-h4: ${ts.h4}rem;
  --pb-scale-body-large: ${ts.bodyLarge}rem;
  --pb-scale-body: ${ts.body}rem;
  --pb-scale-small: ${ts.small}rem;
  --pb-scale-caption: ${ts.caption}rem;
  --pb-line-height-heading: ${ts.lhHeading};
  --pb-line-height-body: ${ts.lhBody};
  --pb-line-height-tight: ${ts.lhTight};

  /* Gradients — toggled by 'Allow gradients' in the configurator.
     When off, both fall back to a flat brand color so muddy color blends are avoided. */
  --pb-allow-gradients: ${allowGradients ? '1' : '0'};
  --pb-gradient-bar: ${allowGradients ? `linear-gradient(90deg, ${accent}, ${secondary})` : secondary};
  --pb-gradient-bg: ${allowGradients ? `linear-gradient(180deg, ${primary}, ${primaryDark})` : primary};
}

/* Logo image replacement — toggles text wordmark to an uploaded image */
.logo-play, .logo-book {
  display: var(--pb-logo-text-display, inline);
}
.card-logo, .badge-logo, .widget-logo, .guide-logo {
  display: inline-flex;
  align-items: center;
}
.card-logo::after, .badge-logo::after, .widget-logo::after, .guide-logo::after {
  content: '';
  display: var(--pb-logo-image-display, none);
  height: var(--pb-logo-image-height, 1.4em);
  background: var(--pb-logo-image, none) no-repeat left center / contain;
  min-width: 4em;
}
` + (appState.logoDataUrl ? `
/* Operator logo (embedded as data URL — no sidecar file needed)
   Mode: ${appState.logoMode} (cobrand = side-by-side with Playbook wordmark, replace = swaps wordmark) */
:root {
  --pb-logo-mode: ${appState.logoMode};
  --pb-logo-image: url('${appState.logoDataUrl}');
  --pb-logo-image-height: 1.4em;${appState.logoMode === 'replace' ? `
  --pb-logo-text-display: none;
  --pb-logo-image-display: inline-block;` : ''}
}
` : '');
}

export function generateFullCss() {
  const meta = {
    program_name: val('programName') || 'Playbook',
    organization: val('orgName'),
    website: val('websiteUrl'),
    helpline_number: val('helplineNumber'),
    text_number: val('textNumber'),
    chat_url: val('chatUrl'),
    min_age: val('minAge'),
    age_disclaimer: (val('disclaimerAge') || 'You must be {{MIN_AGE}}+ to gamble.')
      .replace(/\{\{MIN_AGE\}\}/g, val('minAge') || '21'),
  };
  const metaBlock = '/*! PLAYBOOK_META ' + JSON.stringify(meta) + ' */\n\n';
  return metaBlock + generateVariablesBlock();
}
