import {createRequire} from 'node:module';
import {readFileSync,writeFileSync,mkdtempSync,existsSync,readdirSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
import {createRecipe,validateRecipe,renderArticle} from '../template-system/engine.mjs';
import {loadResources} from '../template-system/resources.mjs';
const require=createRequire(new URL('../render/package.json',import.meta.url)),puppeteer=require('puppeteer');
const url=process.argv[2]||'http://127.0.0.1:8765/collateral/studio/index.html';
const checks=[],errors=[],resources=loadResources(),downloads=mkdtempSync(join(tmpdir(),'playbook-studio-'));
function record(name,pass){checks.push({name,pass:!!pass});assert.ok(pass,name);}
const browser=await puppeteer.launch({headless:true,args:['--no-sandbox']});
const ready=page=>page.waitForFunction(()=>['a','b'].every(s=>document.getElementById('check-'+s).textContent==='Fit, assets and text contrast checked'),{timeout:15000});
try{
 const page=await browser.newPage();await page.setViewport({width:1440,height:1080});
 page.on('pageerror',error=>errors.push(error.message));page.on('requestfailed',request=>{if(request.failure()?.errorText!=='net::ERR_ABORTED')errors.push(request.url());});
 const cdp=await page.createCDPSession();await cdp.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});
 await page.goto(url,{waitUntil:'networkidle0'});await ready(page);
 record('Eight shared templates and seven independent skins',await page.$$eval('#template option',o=>o.length)===8&&await page.$$eval('#skin-a option',o=>o.length)===7);
 record('Preview dimensions match the declared format',await page.$eval('#preview-a',f=>f.contentDocument.querySelector('.specimen').offsetWidth)===1080);
 await page.evaluate(()=>{window.originalArticle=document.getElementById('preview-a').contentDocument.querySelector('.specimen');window.originalMarkup=window.originalArticle.outerHTML;});
 await page.select('#skin-a','club');await ready(page);
 record('CSS skin swaps retain the exact article and media nodes',await page.evaluate(()=>window.originalArticle===document.getElementById('preview-a').contentDocument.querySelector('.specimen')&&window.originalMarkup===window.originalArticle.outerHTML));
 record('Stylesheet changes the visible palette',await page.$eval('#preview-a',f=>f.contentWindow.getComputedStyle(f.contentDocument.querySelector('.specimen')).backgroundColor)==='rgb(23, 60, 53)');
 await page.select('#asset','pause-window');await ready(page);
 record('SVG replaces the photograph in the same media slot',await page.$eval('#preview-a',f=>!!f.contentDocument.querySelector('.mc-photo>svg')&&!f.contentDocument.querySelector('.mc-photo>img')));
 record('SVG inherits each skin’s color',await page.evaluate(()=>{const colors=['a','b'].map(s=>{const f=document.getElementById('preview-'+s);return f.contentWindow.getComputedStyle(f.contentDocument.querySelector('.mc-photo>svg')).color;});return colors[0]!==colors[1];}));
 await page.screenshot({path:'/tmp/playbook-studio-svg-desktop.png',fullPage:true});
 await page.select('#asset','cafe-plan');await ready(page);
 await page.$eval('#crop-y',e=>{e.value='67';e.dispatchEvent(new Event('input',{bubbles:true}));});await ready(page);
 record('Photo selection, alt text and crop travel independently of skin',await page.$eval('#preview-a',f=>{const i=f.contentDocument.querySelector('.mc-photo img');return i.src.includes('cafe-plan')&&i.alt.includes('café')&&f.contentWindow.getComputedStyle(i).objectPosition==='50% 67%';}));
 await page.click('#copy-editor summary');
 await page.$eval('#copy-copy',e=>{e.value='A plan leaves room for the rest of your night.';e.dispatchEvent(new Event('input',{bubbles:true}));});await ready(page);
 await page.waitForFunction(()=>document.getElementById('preview-a').contentDocument.querySelector('.mc-copy').textContent.includes('A plan leaves'));
 record('One content edit updates both live templates',await page.evaluate(()=>['a','b'].every(s=>document.getElementById('preview-'+s).contentDocument.querySelector('.mc-copy').textContent.includes('A plan leaves'))));
 await page.reload({waitUntil:'networkidle0'});await ready(page);
 record('Recipe and comparison skin survive reload',await page.$eval('#copy-copy',e=>e.value)==='A plan leaves room for the rest of your night.'&&await page.$eval('#skin-a',e=>e.value)==='club');
 await page.select('#market','gb-contact');await ready(page);
 record('Market contact and age resolve together',await page.$eval('#preview-a',f=>f.contentDocument.body.innerText.includes('0808 8020 133')&&f.contentDocument.querySelector('.mc-age').innerText==='18+'));
 await page.select('#market','us-contact');await ready(page);
 await page.click('#export-html');await page.waitForFunction(()=>document.getElementById('action-status').textContent.startsWith('Self-contained HTML saved'));
 for(let attempt=0;attempt<50&&!readdirSync(downloads).some(f=>f.endsWith('.html'));attempt++)await new Promise(r=>setTimeout(r,100));
 const htmlPath=join(downloads,readdirSync(downloads).find(f=>f.endsWith('.html'))||'missing');
 record('HTML download is produced',existsSync(htmlPath));
 const exported=readFileSync(htmlPath,'utf8');
 record('Export embeds fonts, image, recipe and market context',exported.includes('data:font/')&&exported.includes('data:image/jpeg')&&exported.includes('id="creative-recipe"')&&exported.includes('export-context')&&!exported.includes('<link'));
 record('Embedded fonts retain copyright notices and license terms',exported.includes('id="font-licenses"')&&exported.includes('2023 Adobe')&&exported.includes('SIL OPEN FONT LICENSE'));
 const offline=await browser.newPage(),outgoing=[];await offline.setViewport({width:1080,height:1350});
 await offline.setRequestInterception(true);offline.on('request',r=>{if(!/^(file:|data:|about:)/.test(r.url())){outgoing.push(r.url());r.abort();}else r.continue();});
 await offline.goto(pathToFileURL(htmlPath).href,{waitUntil:'load'});await offline.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));});
 record('Portable HTML opens without any network request',!outgoing.length&&await offline.$eval('.mc-photo img',i=>i.naturalWidth===2400));await offline.close();
 await page.click('#save-recipe');await page.waitForFunction(()=>document.getElementById('action-status').textContent.startsWith('Recipe saved'));
 for(let attempt=0;attempt<50&&!readdirSync(downloads).some(f=>f.endsWith('.json'));attempt++)await new Promise(r=>setTimeout(r,100));
 const recipePath=join(downloads,readdirSync(downloads).find(f=>f.endsWith('.json')));
 const saved=validateRecipe(JSON.parse(readFileSync(recipePath,'utf8')));
 record('Recipe export retains content, skin, asset and crop',saved.content.copy.startsWith('A plan leaves')&&saved.skinId==='club'&&saved.assetId==='cafe-plan'&&saved.focalPoint[1]===67);
 await page.click('#reset');await ready(page);await(await page.$('#recipe-file')).uploadFile(recipePath);await ready(page);
 record('A saved recipe can be restored',await page.$eval('#copy-copy',e=>e.value)===saved.content.copy&&await page.$eval('#asset',e=>e.value)==='cafe-plan');
 const badFile=join(downloads,'invalid.json');writeFileSync(badFile,JSON.stringify({...saved,assetId:'../../private-photo.jpg'}));await(await page.$('#recipe-file')).uploadFile(badFile);await page.waitForFunction(()=>document.getElementById('action-status').textContent.startsWith('Could not open recipe'));
 record('Invalid imports leave the working recipe intact',await page.$eval('#asset',e=>e.value)==='cafe-plan');
 await page.$eval('#copy-headline',e=>{e.value='W'.repeat(89);e.dispatchEvent(new Event('input',{bubbles:true}));});
 await page.waitForFunction(()=>document.getElementById('check-a').textContent.startsWith('Needs adjustment'));
 record('Overflow is detected and HTML export is blocked',await page.$eval('#export-html',e=>e.disabled));
 await page.click('#reset');await ready(page);
 await page.select('#template','message-protected');await ready(page);await page.select('#skin-a','arcade');await ready(page);
 record('Market warning preserves black-on-white styling across skins',await page.$eval('#preview-a',f=>{const e=f.contentDocument.querySelector('.mc-warning'),s=f.contentWindow.getComputedStyle(e);return s.backgroundColor==='rgb(255, 255, 255)'&&s.color==='rgb(0, 0, 0)'&&e.innerText.includes('1800 858 858');}));
 record('The prescribed market cannot be changed to a generic contact preview',await page.$eval('#market',e=>e.disabled&&e.value==='au-wagering'));
 await page.select('#template','message-support-first');await ready(page);
 record('Support keeps calm typography, no image slot and an actual contact link',await page.$eval('#preview-a',f=>{const d=f.contentDocument;return !d.querySelector('.mc-photo,.mc-plan')&&d.querySelector('.contact-button').href.startsWith('tel:')&&d.querySelector('.mc-contact').compareDocumentPosition(d.querySelector('.mc-copy'))===Node.DOCUMENT_POSITION_FOLLOWING;}));
 await page.select('#template','message-signature');await page.select('#skin-a','atelier');await ready(page);await page.screenshot({path:'/tmp/playbook-studio-desktop.png',fullPage:true});
 await page.setViewport({width:390,height:844});await page.waitForFunction(()=>!document.querySelector('.inspector-shell').open);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.screenshot({path:'/tmp/playbook-studio-mobile.png',fullPage:true});
 record('Mobile workspace has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 const isolated=await browser.newPage();await isolated.evaluateOnNewDocument(()=>{Object.defineProperty(window,'localStorage',{get(){throw new Error('Unavailable');}});});await isolated.goto(url,{waitUntil:'networkidle0'});await ready(isolated);
 record('Editor remains usable when browser storage is unavailable',await isolated.$eval('#save-state',e=>e.textContent.includes('unavailable'))&&!await isolated.$eval('#export-html',e=>e.disabled));await isolated.close();
 const safe=createRecipe('message-signature',{content:{...createRecipe().content,copy:'<img src=x onerror=alert(1)>'}});
 record('Copy is escaped instead of interpreted as HTML',renderArticle(safe,resources).includes('&lt;img src=x onerror=alert(1)&gt;'));
 record('No browser errors',errors.length===0);
}finally{await browser.close();writeFileSync(new URL('./browser-validation.json',import.meta.url),JSON.stringify({checks,errors},null,2)+'\n');}
console.log(`${checks.length} browser and export checks passed. Downloads: ${downloads}`);
